### PR TITLE
Updated CoderData.json

### PR DESCRIPTION
**Pull request by Sarvesh0955**

### CODE REVIEW

**Comment by prateek2105** [comment]
Details Incomplete

**Comment by Sarvesh0955** [comment]
please check now

**Comment by Sarvesh0955** [comment]
Updated CoderData.json

**Comment by Sarvesh0955** [comment]
Issue: https://github.com/opencodeiiita/CodeDigger/issues/2

Updated CoderData.json

**Comment by Sarvesh0955** [comment]
Issue: https://github.com/opencodeiiita/CodeDigger/issues/2

Updated CoderData.json

**Pull request closed without merging**
