### PR TITLE
Created problem 

### PR DESCRIPTION
**Pull request by kyanmahajan**
Issue: #62

### CODE REVIEW

**Comment by rishabhking** [comment]
Rename folder as kyanmahajan-1 instead of githubusername-1.

**Comment by kyanmahajan** [comment]
Sir i have changed now. It was a confusion.

**Comment by rishabhking** [comment]
Your question seems fine but it is very easy and in line number 18 change arr[i]>=0 to arr[i]>0.
Make statement more clearer to solver.
I will accept pr just change above mentioned issue.

**Comment by rishabhking** [comment]
image
Correct english in this para.

**Pull request merged**
